version: '3'
volumes: 
  data:
networks: 
  database:
  web:
  queue:
services: 
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - database
    environment:
      - POSTGRES_PASSWORD=postgres
  frontend:
    image: nginx:1.13
    volumes: 
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    networks: 
      - web
    depends_on: 
      - app
  app:
    image: python:3.6
    volumes: 
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks: 
      - database
      - web
      - queue
    depends_on: 
      - db
      - queue
  queue:
    image: redis:3.2
    networks: 
      - queue
  worker:
    build: worker
    volumes: 
      # Worker
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks: 
      - queue
    depends_on: 
      - queue